### ISSUE TITLE
Disagreement with OTS

### ISSUE THREAD

**Issue by mhosken** [silnrsi/grcompiler#16]
The OTS checking for the Silf table takes, unsurprisingly, a very literal interpretation of the GTF [description](https://github.com/silnrsi/graphite/blob/master/doc/GTF.txt). This includes in which table versions various simple values were given an interpretation and if the table version is less than that given for the use of that value, then the value is considered reserved and must be 0.

This is both wrong and not wrong. It's not wrong in that it is checking that the Silf table conforms to the spec. It's wrong in that such a literal interpretation of the spec does nothing for security and reserved values can be anything. Having said that, it is also wrong that grcompiler outputs tables with too low a version number in many cases. The culprits are:

Field     | Version
----------|-----------
attCollisions | 5
attrMirroring | 4
attrSkipPasses | 4

The structural aspects of how the Silf structure itself changes between versions, is fine. It's just these few values.

**Comment by mhosken** [comment]
Given that grcompiler *always* outputs attrMirroring (why? surely not needed for anything not rtl) and attrSkipPasses, then that means we always have to output at least a v4 Silf table.

**Comment by sharoncorrell** [comment]
This is what I see in the compiler code:

Bidi defaults to false. Mirroring attributes are not defined at all when Bidi = false, let alone output.

Directionality is defined and _some_ (eg, whitespace) attributes are output in any case. But to my knowledge the `directionality` attribute has been defined since the system was first designed, including the field in the Silf table that indicates the `dir` attribute index. (I have solid evidence that it was present in version 2.0 of the table.) So I don't understand how outputting `directionality` superfluously could be problematic.

If the skip-pass optimization is kicking in and creating a problem, it would make more sense to turn that off (-p) than use to an unnecessarily late version of the table.

**Comment by sharoncorrell** [comment]
Another option would be that if they explicitly request v 2 of the Silf table, then make sure skip-passes doesn't happen.

**Comment by sharoncorrell** [comment]
Okay, I lied. Mirror attributes are being output for Padauk. Should not be.

**Comment by sharoncorrell** [comment]
Fixed. The mirror attributes are not defined as glyph attributes unless Bidi = true, which will cause a compilation error if they are used. The *skipPass* attribute is undefined as well, which should not be a problem since it's not something that should be present in GDL. Also we avoid output the collision threshold unless collision avoidance is happening.

**Comment by mhosken** [comment]
>If the skip-pass optimization is kicking in and creating a problem, it would make more sense to turn that off (-p) than use to an unnecessarily late version of the table.

skipPass optimization is so valuable I would argue that it's worth bumping the version. I would be happy with not doing that if -v is specified on the command line. Then I would suggest at least a warning and even an error.

**Comment by sharoncorrell** [comment]
Can this be closed?

**Comment by sharoncorrell** [comment]
Skip-passes is on by default. So the possible combinations are:
* -v 2.0 - the version will be bumped up to 4.0 and a warning given
* -v 2.0 -p - no conflict
* -p - whatever version we need will be used
* no args - whatever version we need will be used - at least 4.0

**Comment by sharoncorrell** [comment]
This is what I have checked in. If the version gets bumped, it is a warning, not an error.

**Comment by sharoncorrell** [comment]
These changes are released, so hopefully they are ok.
