### ISSUE TITLE
compare_PigLatinTest_v2 fails

### ISSUE THREAD

**Issue by bgermann** [silnrsi/grcompiler#36]
Forwarded from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=980699

This is a follow-up on #32. With its fix a9e6dec applied, the test still seems to fail under some condition. The Debian report is for amd64 this time.

**Comment by devosb** [comment]
From talking with @tim-eves I think there are/were two bugs in the testing framework related to the failing test. One bug was fixed last year with https://github.com/silnrsi/grcompiler/commit/a9e6dec71cbc11c5d637fa342e51867330001862 to fix https://github.com/silnrsi/grcompiler/issues/32. There is another bug involving a year timestamp, which is why the error did not show up last year.

The confusing part is both bugs show up with the same message
```
PigLatinTest_v2.ttf" to "/<<PKGBUILDDIR>>/test/GrcRegressionTest/fonts/PigLatinBenchmark_v2.ttf" are different
```

**Comment by nrsiward** [comment]
The unique id in the name table along with several other name ids are changed if the font name is changed. The current year is added to the unique id. When the compiler was developed, we likely didn't think it worth the effort to update the unique id year if no other name table changes were needed.

Since the unique id does have to be changed with a font name change, should we preserve the year from the input ttf?

**Comment by nrsiward** [comment]
We generally preserve the 'unique font id' date field from the input ttf. Also, update the PigLatinBenchmark_v2.ttf. See #9ef83bd
